#include <iostream>
#include <thread>
#include <chrono>
#include <vector>
#include <cstring>
#include <unordered_map>
#include <string>

// Cross-Platform Networking Headers
#ifdef _WIN32
    #include <winsock2.h>
    #include <ws2tcpip.h>
    #pragma comment(lib, "ws2_32.lib")
    typedef int socklen_t;
#else
    #include <sys/types.h>
    #include <sys/socket.h>
    #include <netinet/in.h>
    #include <arpa/inet.h>
    #include <fcntl.h>
    #include <unistd.h>
    #include <errno.h>
    
    typedef int SOCKET;
    const SOCKET INVALID_SOCKET = -1;
    const int SOCKET_ERROR = -1;
    inline int closesocket(SOCKET s) { return close(s); }
#endif

#include "SpatialGrid.hpp"
#include "SessionManager.hpp"

// Updated packet structure with a fixed-size lobby identifier field
struct ClientPacket {
    char lobby_id[32]; // Matches the string ID generated by your Lambda (e.g., "lobby_1741530000")
    uint32_t player_id;
    uint32_t sequence;
    float x;
    float y;
};

struct ServerResponsePacket {
    uint32_t packet_type = 1; 
    uint32_t nearby_count;
};

// Represents an active game match room inside the single server process
struct GameLobby {
    std::string lobby_id;
    SpatialGrid spatial_grid;
    SessionManager session_manager;

    GameLobby(std::string id) : lobby_id(id), spatial_grid(50.0f) {}
};

int main() {
#ifdef _WIN32
    WSADATA wsaData;
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
        std::cerr << "[Error] WSAStartup failed.\n";
        return 1;
    }
#endif

    const double TIMEOUT_SECONDS = 5.0; 
    const auto TICK_RATE = std::chrono::milliseconds(50); // 20 TPS
    const int PORT = 8080;

    SOCKET server_fd = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (server_fd == INVALID_SOCKET) {
        std::cerr << "[Error] Failed to create socket.\n";
#ifdef _WIN32
        WSACleanup();
#endif
        return 1;
    }

    sockaddr_in address{};
    address.sin_family = AF_INET;
    address.sin_addr.s_addr = INADDR_ANY;
    address.sin_port = htons(PORT);

    if (bind(server_fd, (struct sockaddr*)&address, sizeof(address)) == SOCKET_ERROR) {
        std::cerr << "[Error] Failed to bind socket to port " << PORT << ".\n";
        closesocket(server_fd);
#ifdef _WIN32
        WSACleanup();
#endif
        return 1;
    }

#ifdef _WIN32
    u_long mode = 1;
    ioctlsocket(server_fd, FIONBIO, &mode);
#else
    int flags = fcntl(server_fd, F_GETFL, 0);
    fcntl(server_fd, F_SETFL, flags | O_NONBLOCK);
#endif

    std::cout << "[Server] Multi-Lobby UDP Server running on port " << PORT << " at 20 TPS...\n";

    // Central storage tracking all active game rooms in RAM
    std::unordered_map<std::string, GameLobby> active_lobbies;

    char buffer[1024];
    sockaddr_in client_addr{};
    socklen_t client_addr_len = sizeof(client_addr);

    while (true) {
        auto tick_start = std::chrono::steady_clock::now();

        // 1. Ingestion Loop: Read all incoming packets
        while (true) {
            client_addr_len = sizeof(client_addr); 
            int bytes_received = recvfrom(server_fd, buffer, sizeof(buffer), 0,
                                         (struct sockaddr*)&client_addr, &client_addr_len);
            
            if (bytes_received == SOCKET_ERROR) {
#ifdef _WIN32
                if (WSAGetLastError() == WSAEWOULDBLOCK) { break; }
#else
                if (errno == EWOULDBLOCK || errno == EAGAIN) { break; }
#endif
                break; 
            }

            if (bytes_received == sizeof(ClientPacket)) {
                ClientPacket packet;
                std::memcpy(&packet, buffer, sizeof(ClientPacket));
                
                std::string lobby_key(packet.lobby_id);

                // Spin up a new lobby in memory dynamically if it doesn't exist yet
                if (active_lobbies.find(lobby_key) == active_lobbies.end()) {
                    std::cout << "[Server] Spawning new in-memory lobby: " << lobby_key << "\n";
                    active_lobbies.emplace(lobby_key, GameLobby(lobby_key));
                }

                // Route packet data into that specific lobby's managers
                GameLobby& lobby = active_lobbies.at(lobby_key);
                lobby.session_manager.update_activity(packet.player_id, client_addr);
                lobby.spatial_grid.update_player(packet.player_id, packet.x, packet.y);

                auto nearby = lobby.spatial_grid.get_nearby_players(packet.x, packet.y, 1);

                std::cout << "[Lobby: " << lobby_key << "] Player " << packet.player_id 
                          << " | Pos: (" << packet.x << ", " << packet.y << ")"
                          << " | Nearby: " << nearby.size() << "\n";

                // Broadcast player's movement packet to all other peers in the same lobby
                auto active_sessions = lobby.session_manager.get_active_sessions();
                for (const auto& session : active_sessions) {
                    if (session.player_id != packet.player_id) {
                        sendto(server_fd, buffer, bytes_received, 0,
                               (struct sockaddr*)&session.address, sizeof(session.address));
                    }
                }
            }
        }

        // 2. Outbound Broadcast & Maintenance Loop per Lobby
        for (auto it = active_lobbies.begin(); it != active_lobbies.end(); ) {
            GameLobby& lobby = it->second;

            // Broadcast states or acks to active sessions in this lobby
            auto active_sessions = lobby.session_manager.get_active_sessions();
            for (const auto& session : active_sessions) {
                float px = lobby.spatial_grid.get_player_x(session.player_id);
                float py = lobby.spatial_grid.get_player_y(session.player_id);
                auto nearby = lobby.spatial_grid.get_nearby_players(px, py, 1);

                ServerResponsePacket response;
                response.nearby_count = static_cast<uint32_t>(nearby.size());

                sendto(server_fd, (char*)&response, sizeof(response), 0,
                       (struct sockaddr*)&session.address, sizeof(session.address));
            }

            // Prune timed-out players from this lobby
            std::vector<uint32_t> dropped_players = lobby.session_manager.get_timed_out_players(TIMEOUT_SECONDS);
            for (uint32_t dropped_id : dropped_players) {
                lobby.spatial_grid.remove_player(dropped_id);
                std::cout << "[Lobby: " << lobby.lobby_id << "] Player " << dropped_id << " timed out.\n";
            }

            // Optional cleanup: If a lobby becomes completely empty, clear it from RAM to save memory
            if (active_sessions.empty() && !dropped_players.empty()) {
                std::cout << "[Server] Closing empty lobby: " << lobby.lobby_id << "\n";
                it = active_lobbies.erase(it);
            } else {
                ++it;
            }
        }

        // 3. Maintain 20 TPS Tick Rate
        auto tick_end = std::chrono::steady_clock::now();
        auto elapsed = tick_end - tick_start;
        if (elapsed < TICK_RATE) {
            std::this_thread::sleep_for(TICK_RATE - elapsed);
        }
    }

    closesocket(server_fd);
#ifdef _WIN32
    WSACleanup();
#endif
    return 0;
}